<?php

return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'cityMap' => [
        "吉林" => "cn-jl",
        "天津" => "cn-tj",
        "安徽" => "cn-ah",
        "山东" => "cn-sd",
        "山西" => "cn-sx",
        "新疆" => "cn-xj",
        "河北" => "cn-hb",
        "河南" => "cn-he",
        "湖南" => "cn-hn",
        "甘肃" => "cn-gs",
        "福建" => "cn-fj",
        "贵州" => "cn-gz",
        "重庆" => "cn-cq",
        "江苏" => "cn-js",
        "湖北" => "cn-hu",
        "广西" => "cn-gx",
        "云南" => "cn-yn",
        "辽宁" => "cn-ln",
        "香港" => "cn-6668",
        "浙江" => "cn-zj",
        "上海" => "cn-sh",
        "北京" => "cn-bj",
        "广东" => "cn-gd",
        "澳门" => "cn-3681",
        "西藏" => "cn-xz",
        "陕西" => "cn-sa",
        "四川" => "cn-sc",
        "海南" => "cn-ha",
        "宁夏" => "cn-nx",
        "青海" => "cn-qh",
        "江西" => "cn-jx",
        "台湾" => "tw-tw",
        "黑龙江" => "cn-hl",
        "内蒙古" => "cn-nm",
    ]
];
